networks:
  network:
    driver: bridge

volumes:
  postgres-data:

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./dockerfile
    ports:
      - ${BACKEND_PORT}:8080
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    networks:
      - network

  postgres:
    image: postgres:15.12-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network
