networks:
  network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./dockerfile
    ports:
      - ${BACKEND_PORT}:8080
    environment:
      DB_CONNECTION: sqlite
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    networks:
      - network
