networks:
  network:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./dockerfile
    ports:
      - ${FRONTEND_PORT}:5173
    volumes:
      - ./frontend/src:/app/src
    networks:
      - network

  backend:
    build:
      context: ./backend
      dockerfile: ./dockerfile
    ports:
      - ${BACKEND_PORT}:8080
    environment:
      DB_CONNECTION: sqlite
    volumes:
      - ./backend:/app
    networks:
      - network
